### ISSUE TITLE
Weatherbit Rain Today units should be mm/hr instead of mm

### ISSUE THREAD

**Issue by ToastedTortilla** [briis/weatherbit#23]
Based on the current weather API from weatherbit.io, the 'precip' field that I believe is used for this sensor is actually a precipitation rate in mm/hr as opposed to an accumulation value in mm.  This is similar to the 'snow' field and sensor that already use the mm/hr units.

I might be wrong in assuming this value comes from the current weather API (vs. the historical API), but the value fluctuates up and down throughout the day, which seems to line up with this being more of a "how hard is it raining" type of sensor rather than a "how much rain has fallen today" sensor.  Renaming these sensors to "Weatherbit Rain Rate" and "Weatherbit Snow Rate" might be more descriptive, but since it would be a breaking change it's probably best left to the user to override the names if they want.

**Comment by briis** [comment]
Hi @ToastedTortilla 
You are absolutely correct. I just re-read the API Description and *precip* is Precipitation Rate. The sensor has now been renamed, but as I keep the same Unique_Id, it is only a breaking change if you delete and re-add the Integration. The Friendly Name and the Units are now displaying correct value. 
I already had the correct units for *snow*, so I decided not to rename that for now.
Fixed in release 0.31
