### ISSUE TITLE
is_night remaining true during day

### ISSUE THREAD

**Issue by austwhite** [briis/weatherbit#4]
Sorry to be a bother, but this issue seems to have returned.
Sunrise was 7:25am this morning where I am and at 8:30am, the time I am writing this now, the "is_night" flag is still remaining as true.

**Comment by austwhite** [comment]
Okay.  Maybe I was just not patient this morning.
1 hour and 15 mins after sunrise it switched to is_night=false.

Is this a normal time frame to expect?

**Comment by briis** [comment]
Hi @austwhite 
As the data is only refreshed every 30 minutes, there might be some delay, but 1hour and 15min seems too long. I just recently discovered that Weatherbit actually supplies a data value called POD (Part of Day) and that shows d for day and n for night. That might be more accurate than my calculation based on Timezone and Observation Time. I will monitor this for the next few days, and if this better, it will be an easy fix to implement this.

**Comment by austwhite** [comment]
That would be amazing.  That could make it function more like Dark Sky, which I have to totally abandon as it is unavailable yet again, even though it is not officially turned off yet.
Since Apple took over DS, it has been very unreliable and tends to go unavailable a lot.
If the PoD doesn't work, could your component maybe read the Home Assistant `sun.sun` component for `above_horizon` and `below_horizon` ?

**Comment by briis** [comment]
I could use the `sun.sun` but that would only work if HA and the location your get Weather data for, are in the same place. If you add a location in Denmark and one in the US, and your HA installation is in the US, the Icon for Denmark would be wrong. That is why I try to get the data from the observation time for the location in the Weatherbit data.

If you want to test it out right away, go to the `custom_components/weatherbit` folder, and open `manifest. json` and change the below line so that is says 0.10 instead of 0.9 - That uses the POD parameter. If it does not work, just change back to 0.9. Remember to restart HA after the change.

`"requirements": [
      "weatherbitpypi==0.10"
    ],
`

**Comment by austwhite** [comment]
Testing the new version 0.10.   I think it is pretty close to being able to be a version 1.0 :)   I'll monitor it for a few days, but so far it is really good and I like having the selectable update intervals. 
I'll let you know how the day/night thing goes.

**Comment by austwhite** [comment]
Everything working smoothly on my end.  I'll close this now.  Thanks for your help as always.
